var navs = [{
	"title": "基本元素",
	"icon": "fa-cubes",
	"spread": true,
	"children": [{
		"title": "部门管理",
		"icon": "&#xe641;",
		"href": "departmentServletList"
	}, {
		"title": "产品管理",
		"icon": "&#xe63c;",
		"href": "productServletList"
	}, {
		"title": "员工管理",
		"icon": "&#xe63c;",
		"href": "userServletList"
	}, {
		"title": "订单管理",
		"icon": "&#xe609;",
		"href": "ordersServletList"
	}, {
		"title": "消息管理",
		"icon": "&#xe62a;",
		"href": "messageServletList"
	}, {
		"title": "辅助性元素",
		"icon": "&#xe60c;",
		"href": "auxiliar.html"
	}]
}, {
	"title": "组件",
	"icon": "fa-cogs",
	"spread": false,
	"children": [{
		"title": "Datatable",
		"icon": "fa-table",
		"href": "begtable.html"
	}, {
		"title": "Navbar组件",
		"icon": "fa-navicon",
		"href": "navbar.html"
	}, {
		"title": "Laytpl+Laypage",
		"icon": "&#xe628;",
		"href": "paging.html"
	}]
}, {
	"title": "第三方组件",
	"icon": "&#x1002;",
	"spread": false,
	"children": [{
		"title": "iCheck组件",
		"icon": "fa-check-square-o",
		"href": "icheck.html"
	}]
}, {
	"title": "地址本",
	"icon": "fa-address-book",
	"href": "",
	"spread": false,
	"children": [{
		"title": "Github",
		"icon": "fa-github",
		"href": "https://www.github.com/"
	}, {
		"title": "QQ",
		"icon": "fa-qq",
		"href": "http://www.qq.com/"
	}, {
		"title": "Fly社区",
		"icon": "&#xe609;",
		"href": "http://fly.layui.com/"
	}, {
		"title": "新浪微博",
		"icon": "fa-weibo",
		"href": "http://weibo.com/"
	}]
}, {
	"title": "这是一级导航",
	"icon": "fa-stop-circle",
	"href": "https://www.baidu.com",
	"spread": false
}];